# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='media/home/pricings')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='media/home/staff')),
                ('statement', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='classifications',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Designs', 'Designs'), ('App', 'App'), ('Web', 'Web')], default='App', max_length=200),
        ),
        migrations.AddField(
            model_name='topricing',
            name='coCounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prices',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.toPricing'),
        ),
    ]
