# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170626_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInDown', 'bounceInDown'), ('bounceInUp', 'bounceInUp')], default='bounceInLeft', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Web', 'Web'), ('Designs', 'Designs'), ('App', 'App')], default='App', max_length=200),
        ),
    ]
