# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170626_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('bounceInLeft', 'bounceInLeft'), ('bounceInDown', 'bounceInDown'), ('bounceInUp', 'bounceInUp'), ('bounceInRight', 'bounceInRight')], default='bounceInLeft', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Others', 'Others'), ('Web', 'Web'), ('App', 'App')], default='App', max_length=200),
        ),
    ]
