# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170626_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('bounceInDown', 'bounceInDown'), ('bounceInUp', 'bounceInUp'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight')], default='bounceInLeft', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('App', 'App'), ('Web', 'Web'), ('Others', 'Others'), ('Design', 'Design')], default='App', max_length=200),
        ),
    ]
