# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170626_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('bounceInUp', 'bounceInUp'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight')], default='bounceInLeft', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Others', 'Others'), ('App', 'App'), ('Web', 'Web')], default='App', max_length=200),
        ),
    ]
