# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170629_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('bounceInLeft', 'bounceInLeft'), ('bounceInUp', 'bounceInUp'), ('bounceInRight', 'bounceInRight'), ('bounceInDown', 'bounceInDown')], default='bounceInLeft', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('App', 'App'), ('Design', 'Design'), ('Others', 'Others'), ('Web', 'Web')], default='App', max_length=200),
        ),
    ]
