# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170704_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('bounceInRight', 'bounceInRight'), ('bounceInDown', 'bounceInDown'), ('bounceInUp', 'bounceInUp'), ('bounceInLeft', 'bounceInLeft')], default='bounceInLeft', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Design', 'Design'), ('Others', 'Others'), ('App', 'App'), ('Web', 'Web')], default='App', max_length=200),
        ),
    ]
