# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170704_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('bounceInLeft', 'bounceInLeft'), ('bounceInUp', 'bounceInUp'), ('bounceInDown', 'bounceInDown'), ('bounceInRight', 'bounceInRight')], default='bounceInLeft', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('Web', 'Web'), ('App', 'App'), ('Others', 'Others'), ('Design', 'Design')], default='App', max_length=200),
        ),
    ]
