# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='classification',
            field=models.CharField(default='Unread', max_length=50),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='classifications',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=200),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 4, 8, 24, 43, 603868)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 4, 8, 24, 43, 606356)),
        ),
    ]
