# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20170704_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 4, 9, 10, 36, 649678)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 4, 9, 10, 36, 654104)),
        ),
        migrations.AlterField(
            model_name='order',
            name='supporting_doc',
            field=models.FileField(blank=True, null=True, upload_to='media/control'),
        ),
    ]
